// Mocks generated by Mockito 5.3.2 from annotations
// in real_time_chat/test/features/authentication/data/repositories/authentication_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:real_time_chat/features/authentication/data/datasources/authentication_remote_data_source.dart'
    as _i3;
import 'package:real_time_chat/features/authentication/data/models/authentication_response_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationResponseModel_0 extends _i1.SmartFake
    implements _i2.AuthenticationResponseModel {
  _FakeAuthenticationResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class BaseMockAuthenticationRemoteDataSource extends _i1.Mock
    implements _i3.AuthenticationRemoteDataSource {
  @override
  _i4.Future<_i2.AuthenticationResponseModel> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthenticationResponseModel>.value(
            _FakeAuthenticationResponseModel_0(
          this,
          Invocation.method(
            #loginUser,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthenticationResponseModel>.value(
                _FakeAuthenticationResponseModel_0(
          this,
          Invocation.method(
            #loginUser,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthenticationResponseModel>);
  @override
  _i4.Future<_i2.AuthenticationResponseModel> registerUser(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthenticationResponseModel>.value(
            _FakeAuthenticationResponseModel_0(
          this,
          Invocation.method(
            #registerUser,
            [
              name,
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthenticationResponseModel>.value(
                _FakeAuthenticationResponseModel_0(
          this,
          Invocation.method(
            #registerUser,
            [
              name,
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthenticationResponseModel>);
}
